language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8
  
before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - drush make --prepare-install build-vih.make ../vih.dk --yes
  - cd ../vih.dk
  - sudo chmod -R 777 sites/all/modules
  - drush si vih_dk --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="vih.dk" --yes
  - drush cc all --yes
  - cd ../vih.dk-deploy

script: 
  - test -d ../vih.dk/profiles/vih_dk
  - test -d ../vih.dk/sites/all/modules/contrib
  - test -d ../vih.dk/profiles/vih_dk/modules/vih
  - test -d ../vih.dk/profiles/vih_dk/themes
