language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8
  
before_script:
  - "mysql -e 'create database drupal;'"
  - sudo apt-get install drush
  - drush dl drush_make
  - "drush make vih_dk.build --prepare-install ."

script: test.sh
