language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8
  
before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - pear install PHP_CodeSniffer
  - wget http://ftp.drupal.org/files/projects/drupalcs-7.x-1.0-beta1.tar.gz -O ../drupalcs.tar.gz
  - tar -xvzf ../drupalcs.tar.gz -C ../  
  - phpenv rehash
  - drush make vih_dk.build ../vih.dk
  - cd ../vih.dk
  - sudo chmod -R 777 sites/all/modules
  - drush si vih_dk --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="vih.dk" --yes
  - drush cc all --yes

script: 
  - test -d profiles/vih_dk
  - test -d profiles/vih_dk/modules/contrib
  - test -d profiles/vih_dk/modules/vih
  - test -d profiles/vih_dk/themes
  - phpcs . --standard=../drupalcs/Drupal/ruleset.xml --extensions=php,module,inc,install,test,profile,theme
