language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8
  
before_script:
  - "mysql -e 'create database drupal;'"
  - echo "deb http://debian.aegirproject.org stable main" | sudo tee -a /etc/apt/sources.list.d/aegir-stable.list
  - wget -q http://debian.aegirproject.org/key.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install drush
  - drush --version
  - sudo drush self-update

script: bash test.sh
